### ISSUE TITLE
Can you "build" the file's ?

### ISSUE THREAD

**Issue by MadTooth** [jamsilva/chimerasnes#3] opened 2023-04-24 14:23 UTC
I downloaded a [new build of retroarch for PsVita](https://buildbot.libretro.com/stable/1.15.0/playstation/vita/RetroArch.vpk)  [v1.15.0 ~444MB], BUT "chimerasnes_libretro.self" file is missing in "this" build, I use the old version from [Archive.org](https://archive.org/download/chimerasnes_libretro_20221221_2126/vita2d/)

**Comment by jamsilva** [comment] 2023-04-25 20:32
Duplicate of #1.
The core is not yet available in official retroarch builds.
I recently released an updated build.
[Link to reddit announcement](https://www.reddit.com/r/VitaPiracy/comments/12sd444/updated_chimerasnes_libretro_core/)
[Link to the build](https://archive.org/details/chimerasnes)

**Closed as completed by jamsilva** 2023-04-25 20:32 UTC
